name: Format LaTeX

on:
  workflow_dispatch:   # nur manuell starten

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installiere Abhängigkeiten
        run: |
          sudo apt-get update
          sudo apt-get install -y perl
          sudo apt-get install -y texlive
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y cpanminus  # Installiert cpanminus, um Perl-Module zu installieren

      - name: Installiere latexindent
        run: |
          sudo cpanm latexindent  # Installiert latexindent via cpanminus

      - name: Führe latexindent aus
        run: |
          latexindent -w **/*.tex  # Führt latexindent auf allen .tex-Dateien aus
