name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Danke für deinen ersten Issue! 🎉
          Wir schauen uns dein Anliegen so bald wie möglich an.
          Bitte stelle sicher, dass du die [Beitragsrichtlinien](CONTRIBUTING.md) gelesen hast.
        pr-message: |
          Danke für deinen ersten Pull Request! 🎉
          Wir schauen uns deine Änderungen so bald wie möglich an.
          Bitte stelle sicher, dass du die [Beitragsrichtlinien](CONTRIBUTING.md) gelesen hast.
