# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '45 17 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Dieser Issue wurde als veraltet markiert, da er seit 30 Tagen keine Aktivität mehr hatte. Er wird in 7 Tagen geschlossen, wenn keine weiteren Kommentare folgen.'
        stale-pr-message: 'Dieser Pull Request wurde als veraltet markiert, da er seit 30 Tagen keine Aktivität mehr hatte. Er wird in 7 Tagen geschlossen, wenn keine weiteren Kommentare folgen.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
